# Generated by Django 5.0.6 on 2024-06-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_data_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='joined_data',
            new_name='joined_date',
        ),
    ]
