# Generated by Django 5.0.6 on 2024-06-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_joined_data_member_joined_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='firstname',
        ),
    ]
